version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    image: php:8.3-fpm
    container_name: merqueo_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - merqueo-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: merqueo_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
      - "444:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - merqueo-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: merqueo_db
    restart: unless-stopped
    tty: true
    ports:
      - "3310:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: merqueo_db
      MYSQL_ROOT_PASSWORD: toor
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - merqueo-network

#Docker Networks
networks:
  merqueo-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
